- hosts: all
  become: true
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install latest version of Certbot
      apt: name={{ item }} state=latest
      with_items:
        - certbot
        - python3-certbot-nginx

    - name: Setup Certbot account and install certificates
      shell: certbot --nginx --non-interactive --agree-tos --email {{ email }} --domains {{ host_uri }},www.{{ host_uri }} --register-unsafely-without-email
